// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelroute"
)

// GroupModelRoute is the model entity for the GroupModelRoute schema.
type GroupModelRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 源分组 ID（api_key 绑定的分组）
	GroupID int64 `json:"group_id,omitempty"`
	// 模型模式，支持末尾 * 通配，如 grok-4.5 或 grok-*
	ModelPattern string `json:"model_pattern,omitempty"`
	// 目标分组 ID，命中后请求改由该分组调度
	TargetGroupID int64 `json:"target_group_id,omitempty"`
	// 同长度模式命中时的二级决相，数字越小越优先；主排序是模式最长优先
	Priority int `json:"priority,omitempty"`
	// 是否启用，关闭后立即回落源分组行为
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupModelRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupmodelroute.FieldEnabled:
			values[i] = new(sql.NullBool)
		case groupmodelroute.FieldID, groupmodelroute.FieldGroupID, groupmodelroute.FieldTargetGroupID, groupmodelroute.FieldPriority:
			values[i] = new(sql.NullInt64)
		case groupmodelroute.FieldModelPattern:
			values[i] = new(sql.NullString)
		case groupmodelroute.FieldCreatedAt, groupmodelroute.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupModelRoute fields.
func (_m *GroupModelRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupmodelroute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupmodelroute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupmodelroute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case groupmodelroute.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupmodelroute.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case groupmodelroute.FieldTargetGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_group_id", values[i])
			} else if value.Valid {
				_m.TargetGroupID = value.Int64
			}
		case groupmodelroute.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case groupmodelroute.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupModelRoute.
// This includes values selected through modifiers, order, etc.
func (_m *GroupModelRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupModelRoute.
// Note that you need to call GroupModelRoute.Unwrap() before calling this method if this GroupModelRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupModelRoute) Update() *GroupModelRouteUpdateOne {
	return NewGroupModelRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupModelRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupModelRoute) Unwrap() *GroupModelRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupModelRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupModelRoute) String() string {
	var builder strings.Builder
	builder.WriteString("GroupModelRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("target_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetGroupID))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// GroupModelRoutes is a parsable slice of GroupModelRoute.
type GroupModelRoutes []*GroupModelRoute
