// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupModelRouteUpdate is the builder for updating GroupModelRoute entities.
type GroupModelRouteUpdate struct {
	config
	hooks    []Hook
	mutation *GroupModelRouteMutation
}

// Where appends a list predicates to the GroupModelRouteUpdate builder.
func (_u *GroupModelRouteUpdate) Where(ps ...predicate.GroupModelRoute) *GroupModelRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupModelRouteUpdate) SetUpdatedAt(v time.Time) *GroupModelRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupModelRouteUpdate) SetGroupID(v int64) *GroupModelRouteUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupModelRouteUpdate) SetNillableGroupID(v *int64) *GroupModelRouteUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupModelRouteUpdate) AddGroupID(v int64) *GroupModelRouteUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *GroupModelRouteUpdate) SetModelPattern(v string) *GroupModelRouteUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *GroupModelRouteUpdate) SetNillableModelPattern(v *string) *GroupModelRouteUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *GroupModelRouteUpdate) SetTargetGroupID(v int64) *GroupModelRouteUpdate {
	_u.mutation.ResetTargetGroupID()
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *GroupModelRouteUpdate) SetNillableTargetGroupID(v *int64) *GroupModelRouteUpdate {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// AddTargetGroupID adds value to the "target_group_id" field.
func (_u *GroupModelRouteUpdate) AddTargetGroupID(v int64) *GroupModelRouteUpdate {
	_u.mutation.AddTargetGroupID(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GroupModelRouteUpdate) SetPriority(v int) *GroupModelRouteUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GroupModelRouteUpdate) SetNillablePriority(v *int) *GroupModelRouteUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GroupModelRouteUpdate) AddPriority(v int) *GroupModelRouteUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GroupModelRouteUpdate) SetEnabled(v bool) *GroupModelRouteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GroupModelRouteUpdate) SetNillableEnabled(v *bool) *GroupModelRouteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the GroupModelRouteMutation object of the builder.
func (_u *GroupModelRouteUpdate) Mutation() *GroupModelRouteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupModelRouteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupModelRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupModelRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupModelRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupModelRouteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupmodelroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupModelRouteUpdate) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := groupmodelroute.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "GroupModelRoute.model_pattern": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupModelRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmodelroute.Table, groupmodelroute.Columns, sqlgraph.NewFieldSpec(groupmodelroute.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupmodelroute.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupmodelroute.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(groupmodelroute.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetGroupID(); ok {
		_spec.SetField(groupmodelroute.FieldTargetGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetGroupID(); ok {
		_spec.AddField(groupmodelroute.FieldTargetGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(groupmodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(groupmodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(groupmodelroute.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmodelroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupModelRouteUpdateOne is the builder for updating a single GroupModelRoute entity.
type GroupModelRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupModelRouteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupModelRouteUpdateOne) SetUpdatedAt(v time.Time) *GroupModelRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupModelRouteUpdateOne) SetGroupID(v int64) *GroupModelRouteUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupModelRouteUpdateOne) SetNillableGroupID(v *int64) *GroupModelRouteUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupModelRouteUpdateOne) AddGroupID(v int64) *GroupModelRouteUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *GroupModelRouteUpdateOne) SetModelPattern(v string) *GroupModelRouteUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *GroupModelRouteUpdateOne) SetNillableModelPattern(v *string) *GroupModelRouteUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *GroupModelRouteUpdateOne) SetTargetGroupID(v int64) *GroupModelRouteUpdateOne {
	_u.mutation.ResetTargetGroupID()
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *GroupModelRouteUpdateOne) SetNillableTargetGroupID(v *int64) *GroupModelRouteUpdateOne {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// AddTargetGroupID adds value to the "target_group_id" field.
func (_u *GroupModelRouteUpdateOne) AddTargetGroupID(v int64) *GroupModelRouteUpdateOne {
	_u.mutation.AddTargetGroupID(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GroupModelRouteUpdateOne) SetPriority(v int) *GroupModelRouteUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GroupModelRouteUpdateOne) SetNillablePriority(v *int) *GroupModelRouteUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GroupModelRouteUpdateOne) AddPriority(v int) *GroupModelRouteUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GroupModelRouteUpdateOne) SetEnabled(v bool) *GroupModelRouteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GroupModelRouteUpdateOne) SetNillableEnabled(v *bool) *GroupModelRouteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the GroupModelRouteMutation object of the builder.
func (_u *GroupModelRouteUpdateOne) Mutation() *GroupModelRouteMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupModelRouteUpdate builder.
func (_u *GroupModelRouteUpdateOne) Where(ps ...predicate.GroupModelRoute) *GroupModelRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupModelRouteUpdateOne) Select(field string, fields ...string) *GroupModelRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupModelRoute entity.
func (_u *GroupModelRouteUpdateOne) Save(ctx context.Context) (*GroupModelRoute, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupModelRouteUpdateOne) SaveX(ctx context.Context) *GroupModelRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupModelRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupModelRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupModelRouteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupmodelroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupModelRouteUpdateOne) check() error {
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := groupmodelroute.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "GroupModelRoute.model_pattern": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupModelRouteUpdateOne) sqlSave(ctx context.Context) (_node *GroupModelRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmodelroute.Table, groupmodelroute.Columns, sqlgraph.NewFieldSpec(groupmodelroute.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupModelRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmodelroute.FieldID)
		for _, f := range fields {
			if !groupmodelroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupmodelroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(groupmodelroute.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(groupmodelroute.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(groupmodelroute.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetGroupID(); ok {
		_spec.SetField(groupmodelroute.FieldTargetGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetGroupID(); ok {
		_spec.AddField(groupmodelroute.FieldTargetGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(groupmodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(groupmodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(groupmodelroute.FieldEnabled, field.TypeBool, value)
	}
	_node = &GroupModelRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmodelroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
