// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupModelRouteDelete is the builder for deleting a GroupModelRoute entity.
type GroupModelRouteDelete struct {
	config
	hooks    []Hook
	mutation *GroupModelRouteMutation
}

// Where appends a list predicates to the GroupModelRouteDelete builder.
func (_d *GroupModelRouteDelete) Where(ps ...predicate.GroupModelRoute) *GroupModelRouteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupModelRouteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupModelRouteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupModelRouteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupmodelroute.Table, sqlgraph.NewFieldSpec(groupmodelroute.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupModelRouteDeleteOne is the builder for deleting a single GroupModelRoute entity.
type GroupModelRouteDeleteOne struct {
	_d *GroupModelRouteDelete
}

// Where appends a list predicates to the GroupModelRouteDelete builder.
func (_d *GroupModelRouteDeleteOne) Where(ps ...predicate.GroupModelRoute) *GroupModelRouteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupModelRouteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupmodelroute.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupModelRouteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
