// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelroute"
)

// GroupModelRouteCreate is the builder for creating a GroupModelRoute entity.
type GroupModelRouteCreate struct {
	config
	mutation *GroupModelRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupModelRouteCreate) SetCreatedAt(v time.Time) *GroupModelRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupModelRouteCreate) SetNillableCreatedAt(v *time.Time) *GroupModelRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupModelRouteCreate) SetUpdatedAt(v time.Time) *GroupModelRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupModelRouteCreate) SetNillableUpdatedAt(v *time.Time) *GroupModelRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupModelRouteCreate) SetGroupID(v int64) *GroupModelRouteCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModelPattern sets the "model_pattern" field.
func (_c *GroupModelRouteCreate) SetModelPattern(v string) *GroupModelRouteCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetTargetGroupID sets the "target_group_id" field.
func (_c *GroupModelRouteCreate) SetTargetGroupID(v int64) *GroupModelRouteCreate {
	_c.mutation.SetTargetGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *GroupModelRouteCreate) SetEnabled(v bool) *GroupModelRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *GroupModelRouteCreate) SetNillableEnabled(v *bool) *GroupModelRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the GroupModelRouteMutation object of the builder.
func (_c *GroupModelRouteCreate) Mutation() *GroupModelRouteMutation {
	return _c.mutation
}

// Save creates the GroupModelRoute in the database.
func (_c *GroupModelRouteCreate) Save(ctx context.Context) (*GroupModelRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupModelRouteCreate) SaveX(ctx context.Context) *GroupModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupModelRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupModelRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupModelRouteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupmodelroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groupmodelroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := groupmodelroute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupModelRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupModelRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupModelRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupModelRoute.group_id"`)}
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "GroupModelRoute.model_pattern"`)}
	}
	if v, ok := _c.mutation.ModelPattern(); ok {
		if err := groupmodelroute.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "GroupModelRoute.model_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetGroupID(); !ok {
		return &ValidationError{Name: "target_group_id", err: errors.New(`ent: missing required field "GroupModelRoute.target_group_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "GroupModelRoute.enabled"`)}
	}
	return nil
}

func (_c *GroupModelRouteCreate) sqlSave(ctx context.Context) (*GroupModelRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupModelRouteCreate) createSpec() (*GroupModelRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupModelRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupmodelroute.Table, sqlgraph.NewFieldSpec(groupmodelroute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupmodelroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(groupmodelroute.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(groupmodelroute.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.TargetGroupID(); ok {
		_spec.SetField(groupmodelroute.FieldTargetGroupID, field.TypeInt64, value)
		_node.TargetGroupID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(groupmodelroute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupModelRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupModelRouteCreate) OnConflict(opts ...sql.ConflictOption) *GroupModelRouteUpsertOne {
	_c.conflict = opts
	return &GroupModelRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupModelRouteCreate) OnConflictColumns(columns ...string) *GroupModelRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupModelRouteUpsertOne{
		create: _c,
	}
}

type (
	// GroupModelRouteUpsertOne is the builder for "upsert"-ing
	//  one GroupModelRoute node.
	GroupModelRouteUpsertOne struct {
		create *GroupModelRouteCreate
	}

	// GroupModelRouteUpsert is the "OnConflict" setter.
	GroupModelRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRouteUpsert) SetUpdatedAt(v time.Time) *GroupModelRouteUpsert {
	u.Set(groupmodelroute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRouteUpsert) UpdateUpdatedAt() *GroupModelRouteUpsert {
	u.SetExcluded(groupmodelroute.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupModelRouteUpsert) SetGroupID(v int64) *GroupModelRouteUpsert {
	u.Set(groupmodelroute.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsert) UpdateGroupID() *GroupModelRouteUpsert {
	u.SetExcluded(groupmodelroute.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupModelRouteUpsert) AddGroupID(v int64) *GroupModelRouteUpsert {
	u.Add(groupmodelroute.FieldGroupID, v)
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *GroupModelRouteUpsert) SetModelPattern(v string) *GroupModelRouteUpsert {
	u.Set(groupmodelroute.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *GroupModelRouteUpsert) UpdateModelPattern() *GroupModelRouteUpsert {
	u.SetExcluded(groupmodelroute.FieldModelPattern)
	return u
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *GroupModelRouteUpsert) SetTargetGroupID(v int64) *GroupModelRouteUpsert {
	u.Set(groupmodelroute.FieldTargetGroupID, v)
	return u
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsert) UpdateTargetGroupID() *GroupModelRouteUpsert {
	u.SetExcluded(groupmodelroute.FieldTargetGroupID)
	return u
}

// AddTargetGroupID adds v to the "target_group_id" field.
func (u *GroupModelRouteUpsert) AddTargetGroupID(v int64) *GroupModelRouteUpsert {
	u.Add(groupmodelroute.FieldTargetGroupID, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *GroupModelRouteUpsert) SetEnabled(v bool) *GroupModelRouteUpsert {
	u.Set(groupmodelroute.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupModelRouteUpsert) UpdateEnabled() *GroupModelRouteUpsert {
	u.SetExcluded(groupmodelroute.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupModelRouteUpsertOne) UpdateNewValues() *GroupModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupmodelroute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupModelRouteUpsertOne) Ignore() *GroupModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupModelRouteUpsertOne) DoNothing() *GroupModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupModelRouteCreate.OnConflict
// documentation for more info.
func (u *GroupModelRouteUpsertOne) Update(set func(*GroupModelRouteUpsert)) *GroupModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRouteUpsertOne) SetUpdatedAt(v time.Time) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRouteUpsertOne) UpdateUpdatedAt() *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupModelRouteUpsertOne) SetGroupID(v int64) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupModelRouteUpsertOne) AddGroupID(v int64) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsertOne) UpdateGroupID() *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *GroupModelRouteUpsertOne) SetModelPattern(v string) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *GroupModelRouteUpsertOne) UpdateModelPattern() *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateModelPattern()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *GroupModelRouteUpsertOne) SetTargetGroupID(v int64) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetTargetGroupID(v)
	})
}

// AddTargetGroupID adds v to the "target_group_id" field.
func (u *GroupModelRouteUpsertOne) AddTargetGroupID(v int64) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.AddTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsertOne) UpdateTargetGroupID() *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GroupModelRouteUpsertOne) SetEnabled(v bool) *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupModelRouteUpsertOne) UpdateEnabled() *GroupModelRouteUpsertOne {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *GroupModelRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupModelRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupModelRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupModelRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupModelRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupModelRouteCreateBulk is the builder for creating many GroupModelRoute entities in bulk.
type GroupModelRouteCreateBulk struct {
	config
	err      error
	builders []*GroupModelRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupModelRoute entities in the database.
func (_c *GroupModelRouteCreateBulk) Save(ctx context.Context) ([]*GroupModelRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupModelRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupModelRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupModelRouteCreateBulk) SaveX(ctx context.Context) []*GroupModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupModelRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupModelRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupModelRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupModelRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupModelRouteUpsertBulk {
	_c.conflict = opts
	return &GroupModelRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupModelRouteCreateBulk) OnConflictColumns(columns ...string) *GroupModelRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupModelRouteUpsertBulk{
		create: _c,
	}
}

// GroupModelRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupModelRoute nodes.
type GroupModelRouteUpsertBulk struct {
	create *GroupModelRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupModelRouteUpsertBulk) UpdateNewValues() *GroupModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupmodelroute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupModelRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupModelRouteUpsertBulk) Ignore() *GroupModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupModelRouteUpsertBulk) DoNothing() *GroupModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupModelRouteCreateBulk.OnConflict
// documentation for more info.
func (u *GroupModelRouteUpsertBulk) Update(set func(*GroupModelRouteUpsert)) *GroupModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRouteUpsertBulk) SetUpdatedAt(v time.Time) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRouteUpsertBulk) UpdateUpdatedAt() *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupModelRouteUpsertBulk) SetGroupID(v int64) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupModelRouteUpsertBulk) AddGroupID(v int64) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsertBulk) UpdateGroupID() *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *GroupModelRouteUpsertBulk) SetModelPattern(v string) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *GroupModelRouteUpsertBulk) UpdateModelPattern() *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateModelPattern()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *GroupModelRouteUpsertBulk) SetTargetGroupID(v int64) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetTargetGroupID(v)
	})
}

// AddTargetGroupID adds v to the "target_group_id" field.
func (u *GroupModelRouteUpsertBulk) AddTargetGroupID(v int64) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.AddTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *GroupModelRouteUpsertBulk) UpdateTargetGroupID() *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GroupModelRouteUpsertBulk) SetEnabled(v bool) *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupModelRouteUpsertBulk) UpdateEnabled() *GroupModelRouteUpsertBulk {
	return u.Update(func(s *GroupModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *GroupModelRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupModelRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupModelRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupModelRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
