// Code generated by ent, DO NOT EDIT.

package groupmodelroute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldGroupID, v))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldModelPattern, v))
}

// TargetGroupID applies equality check predicate on the "target_group_id" field. It's identical to TargetGroupIDEQ.
func TargetGroupID(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldTargetGroupID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldGroupID, v))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldContainsFold(FieldModelPattern, v))
}

// TargetGroupIDEQ applies the EQ predicate on the "target_group_id" field.
func TargetGroupIDEQ(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldTargetGroupID, v))
}

// TargetGroupIDNEQ applies the NEQ predicate on the "target_group_id" field.
func TargetGroupIDNEQ(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldTargetGroupID, v))
}

// TargetGroupIDIn applies the In predicate on the "target_group_id" field.
func TargetGroupIDIn(vs ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldTargetGroupID, vs...))
}

// TargetGroupIDNotIn applies the NotIn predicate on the "target_group_id" field.
func TargetGroupIDNotIn(vs ...int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldTargetGroupID, vs...))
}

// TargetGroupIDGT applies the GT predicate on the "target_group_id" field.
func TargetGroupIDGT(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldTargetGroupID, v))
}

// TargetGroupIDGTE applies the GTE predicate on the "target_group_id" field.
func TargetGroupIDGTE(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldTargetGroupID, v))
}

// TargetGroupIDLT applies the LT predicate on the "target_group_id" field.
func TargetGroupIDLT(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldTargetGroupID, v))
}

// TargetGroupIDLTE applies the LTE predicate on the "target_group_id" field.
func TargetGroupIDLTE(v int64) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldTargetGroupID, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupModelRoute) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupModelRoute) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupModelRoute) predicate.GroupModelRoute {
	return predicate.GroupModelRoute(sql.NotPredicates(p))
}
